name: Appcast

on:
  push:
    branches: [main]
  release:
    types: [published]
  workflow_dispatch:

jobs:
  call-workflow:
    uses: sindresorhus/appcast-workflow/.github/workflows/appcast.yml@main
    secrets:
      SPARKLE_PRIVATE_KEY: "{{ secrets.SPARKLE_PRIVATE_KEY }}"
    permissions:
      pages: write
      id-token: write
